name: NPM Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x, 14.x]
        generator-version: [2.0.5, latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install yeoman-generator@${{ matrix.generator-version }}
    - run: npm test
      env:
        CI: true
