name: Create tag

on:
  milestone:
    types: [closed]

jobs:
  milestone_reached:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - run: |
          npm version ${{github.event.milestone.title}}
          git add package*.json
          git config --local user.email "mshima@users.noreply.github.com"
          git config --local user.name "Marcelo Shima"
          git commit -m "${{github.event.milestone.title}}"
          git push
          git tag ${{github.event.milestone.title}}
          git push origin ${{github.event.milestone.title}}
