name: Create tag

on:
  milestone:
    types: [closed]

jobs:
  milestone_reached:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git remote add github "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git pull github ${GITHUB_REF} --ff-only
          git config --global user.email "mshima@users.noreply.github.com"
          git config --global user.name "Marcelo Shima"
          npm version ${{github.event.milestone.title}}
          git push github HEAD:${GITHUB_REF}
          git push github ${{github.event.milestone.title}}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.event.milestone.title}}
          release_name: Release ${{github.event.milestone.title}}
          body: ${{github.event.milestone.description}}
          draft: true
          prerelease: false
          